# Generated by Django 4.1.5 on 2023-01-23 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameMatchWord', '0002_vocabulary_treasury_alter_user_email_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vocabulary_Treasury',
            new_name='Treasury',
        ),
    ]
