# Generated by Django 4.1.5 on 2023-01-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameMatchWord', '0003_rename_vocabulary_treasury_treasury'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vocab_type', models.CharField(max_length=1)),
            ],
        ),
        migrations.DeleteModel(
            name='Treasury',
        ),
    ]
