# Generated by Django 4.1.5 on 2023-01-23 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameMatchWord', '0004_vocabulary_delete_treasury'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vocabulary',
        ),
    ]
