# Generated by Django 4.1.5 on 2023-01-25 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameMatchWord', '0006_vocabulary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treasury',
            fields=[
                ('treasury_id', models.AutoField(primary_key=True, serialize=False)),
                ('treasury_title', models.CharField(blank=True, max_length=10)),
                ('treasury_date', models.DateField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Vocabulary',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
