# Generated by Django 4.1.5 on 2023-01-25 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameMatchWord', '0007_treasury_delete_vocabulary_remove_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='id',
        ),
    ]
