# Generated by Django 4.1.5 on 2023-01-25 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameMatchWord', '0008_rename_user_id_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='id',
            new_name='user_id',
        ),
    ]
