# Generated by Django 4.1.5 on 2023-01-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameMatchWord', '0009_rename_id_user_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='treasury_id',
            field=models.ManyToManyField(to='gameMatchWord.treasury'),
        ),
    ]
