# Generated by Django 4.1.5 on 2023-01-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameMatchWord', '0010_user_treasury_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('score_id', models.AutoField(primary_key=True, serialize=False)),
                ('treasury_title', models.CharField(blank=True, max_length=10)),
                ('score', models.IntegerField(blank=True)),
                ('vocab_correct', models.CharField(blank=True, max_length=100)),
                ('vocab_wrong', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
