# Generated by Django 4.1.5 on 2023-01-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameMatchWord', '0011_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='treasury_title',
        ),
        migrations.AddField(
            model_name='score',
            name='treasury_id',
            field=models.ManyToManyField(to='gameMatchWord.treasury'),
        ),
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vocabulary', models.CharField(blank=True, max_length=30)),
                ('thai_vocab', models.CharField(blank=True, max_length=30)),
                ('vocab_type', models.CharField(blank=True, max_length=1)),
                ('treasury_id', models.ManyToManyField(to='gameMatchWord.treasury')),
            ],
        ),
    ]
