# Generated by Django 4.1.6 on 2023-02-05 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameMatchWord', '0014_treasury_total_vocab'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vocabulary',
            name='vocab_type',
        ),
    ]
