# Generated by Django 4.1.6 on 2023-02-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameMatchWord', '0016_delete_vocabulary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('vocabulary_id', models.AutoField(primary_key=True, serialize=False)),
                ('vocabulary', models.CharField(blank=True, max_length=30)),
                ('thai_vocab', models.CharField(blank=True, max_length=30)),
                ('treasury_id', models.ManyToManyField(to='gameMatchWord.treasury')),
            ],
        ),
    ]
